site_name: Ghid Tehnic BrickBot
site_url: https://brickbot-guide.com/

repo_url: https://github.com/BrickBot15996/brickbot-docs
repo_name: brickbot-docs

# plugins:
#   - git-revision-date-localized:
#       enable_creation_date: true
#       fallback_to_build_date: true
#       type: date
#       format: "YYYY-MM-DD HH:mm"
#       locale: "en"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - toc.follow
    - search
    - search.suggest
    - navigation.footer
    - offline
  font:
    text: "Inter"
    code: "JetBrains Mono"
  language: ro
  favicon: media/brick_yellow.png
  logo: media/brick_yellow.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brickbotcnu
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/brickbotcnu
    - icon: fontawesome/solid/envelope
      link: mailto:brickbot@liceulunirea.ro
    - icon: fontawesome/solid/globe
      link: https://brickbot.ro

extra_css:
  - styles/theme-switch.css # Custom CSS to switch themes
nav:
  - Acasă: index.md
  - Introducere:
      - Ce este FTC?: intro/ce-este-ftc.md
      - Mentalitate de succes: intro/mentalitatea-castigatoare.md
  - CAD:
      - Ce este CAD?: cad/cad.md
      - Onshape: cad/onshape.md
  - Mecanică:
      - toBeCompleted: assembly/idkyet.md
  - Programare:
      - Android Studio: programming/android-studio.md
      - Java: programming/java.md
      - SimplicityFTC: programming/simplicityftc.md
      - Alte resurse: programming/other-resources.md
