site_name: Ghid Introductiv BrickBot
site_url: https://brickbot-guide.com/

repo_url: https://github.com/BrickBot15996/brickbot-docs
repo_name: brickbot-docs

# plugins:
#   - git-revision-date-localized:
#       enable_creation_date: true
#       fallback_to_build_date: true
#       type: date
#       format: "YYYY-MM-DD HH:mm"
#       locale: "en"

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - toc.follow
    - search
    - search.suggest
    - navigation.footer
    - offline
  font:
    text: "Inter"
    code: "JetBrains Mono"
  language: ro
  favicon: media/brick_yellow.png
  logo: media/brick_yellow.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brickbotcnu
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/brickbotcnu
    - icon: fontawesome/solid/envelope
      link: mailto:brickbot@liceulunirea.ro # FIXME: FIXXXXXXXXXXXXXXXXXXXXXX
    - icon: fontawesome/solid/globe
      link: https://brickbot.ro

extra_css:
  - styles/stylesheet.css # Custom CSS to switch themes
nav:
  - Acasă: index.md
  - Introducere:
      - Ce este FTC?: intro/what-is-ftc.md
      - Mentalitate de succes: intro/right-mentality.md
  - Proiectare 3D:
      - Ce este Proiectarea 3D?: cad/cad.md
      - Onshape: cad/onshape.md
      - Printarea 3D: cad/3d-printing.md
  - Mecanică:
      - Concepte necesare: assembly/basic-concepts.md
      - Furnizori principali: assembly/vendors.md
      - Componentele electronice: assembly/electrical.md
      - Componentele mecanice: assembly/mechanical.md
      - Mecanisme des întâlnite: assembly/mechanisms.md
      - Cum se concepe un robot?: assembly/robot.md
      - Cum îți faci robotul ușor de condus?: assembly/driveable-robot.md
      - Cablare: assembly/wiring.md
  - Programare:
      - Android Studio: programming/android-studio.md
      - Java: programming/java.md
      - Java în FTC: programming/java-in-ftc.md
      - Teoria controlului: programming/control-theory.md
      - SimplicityFTC: programming/simplicityftc.md
      - Alte resurse: programming/other-resources.md
  - Portofoliul Inginerului:
      - Introducere: portfolio/introduction.md
      - Tehnic: portfolio/technical.md
      - Non-Tehnic: portfolio/non-technical.md